apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: model
  name: model
spec:
  type: NodePort
  ports:
  - name: "28101"
    port: 28101
    targetPort: 28101
  selector:
    app: model
status:
  loadBalancer: {}
