apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: model
  name: model
spec:
  revisionHistoryLimit: 5
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model
    spec:
      containers:
      - env:
        - name: jdbc_url
          value: jdbc:postgresql://db:5432/
        image: slisson/webmps-model:201912030949
        imagePullPolicy: IfNotPresent
        name: model
        ports:
        - containerPort: 28101
        - containerPort: 5071
          name: "jvm-debug"        
        resources: 
          requests:
            memory: "600Mi"
            cpu: "0.1"
          limits:
            memory: "800Mi"
            cpu: "1.0"
        readinessProbe:
          tcpSocket:
            port: 28101
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 28101
          initialDelaySeconds: 60
          periodSeconds: 10
      restartPolicy: Always
status: {}
