apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth
  name: oauth
spec:
  type: NodePort
  ports:
    - port: 4180
      name: "http"
      protocol: TCP
      targetPort: 4180
    - port: 4181
      name: "https"
      protocol: TCP
      targetPort: 4181
  selector:
    app: oauth
