apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
      - name: ui
        image: eu.gcr.io/cloudmps-250805/webmps-ui
        imagePullPolicy: IfNotPresent
        env:
        - name: MODEL_URI
          value: ws://model:28101/
        ports:
        - containerPort: 33333
        resources: 
          requests:
            memory: "1Gi"
            cpu: "0.4"
          limits:
            memory: "1.5Gi"
            cpu: "1.0"
        readinessProbe:
          httpGet:
            path: /repositoryAsHtml
            port: 33333
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 60
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /repositoryAsHtml
            port: 33333
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 3
      restartPolicy: Always
status: {}
