apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
      - name: ui
        image: eu.gcr.io/webmps/webmps-ui:201910171554
        imagePullPolicy: IfNotPresent
        env:
        - name: MODEL_URI
          value: ws://model:28101/ws
        ports:
        - containerPort: 33333
        resources: 
          requests:
            memory: "1.5Gi"
            cpu: "0.8"
          limits:
            memory: "2Gi"
            cpu: "1.5"
        readinessProbe:
          httpGet:
            path: /health
            port: 33333
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 33333
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 10
      restartPolicy: Always
status: {}
