apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"ui-backendconfig"}}'
  creationTimestamp: null
  labels:
    app: ui
  name: ui
spec:
  type: NodePort
  ports:
  - name: "8093"
    port: 8093
    targetPort: 33333
  selector:
    app: ui
status:
  loadBalancer: {}
