apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: ui-backendconfig
spec:
  timeoutSec: 300
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 0