apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: model
  name: model
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: model
    spec:
      containers:
      - env:
        - name: jdbc_url
          value: jdbc:postgresql://db:5432/
        image: webmps-model
        imagePullPolicy: Never
        name: model
        ports:
        - containerPort: 28101
        resources: {}
      restartPolicy: Always
status: {}
